lista_2 = []
print(f"Los valores de mi lista son: {lista_2}")
lista_2.append(2.7)
lista_2.append(3.5443)
lista_2.append(0.26)
lista_2.append(1)
lista_2.append(2)
lista_2.append(3)
lista_2.append("Hola")
lista_2.append("siu")
lista_2.append("Python")
print(f"Los valores actualizados de mi lista_2 son: {lista_2}")